### ISSUE TITLE
error during connect: Get "https://<camera_ip>:2376/v1.24/version": x509: certificate is valid for 10.10.10.20, 127.0.0.1, not <camera_ip>

### ISSUE THREAD

**Issue by Duckypu** [AxisCommunications/docker-acap#73]
Hi, I was running the tutorial to setup the Docker ACAP. I've successfully generated the required keys and certificates via the official [docker documentation](https://docs.docker.com/engine/security/protect-access/). However, when I run the following instruction:

```
docker --tlsverify \
       --tlscacert=ca.pem \
       --tlscert=cert.pem \
       --tlskey=key.pem \
       -H=<axis_device_ip>:2376 \
       version
```

And I received:

> Client: Docker Engine - Community
>  Version:           20.10.8
>  API version:       1.41
>  Go version:        go1.16.6
>  Git commit:        3967b7d
>  Built:             Fri Jul 30 19:54:08 2021
>  OS/Arch:           linux/amd64
>  Context:           default
>  Experimental:      true
> error during connect: Get "https://172.16.15.79:2376/v1.24/version": x509: certificate is valid for 10.10.10.20, 127.0.0.1, not 172.16.15.79

 
How can I solve it?

### Environment

- Axis device model: AXIS P3265-LVE
- Axis device firmware version: 10.11.76
- OS and version: Ubuntu 18.04.4 LTS
- Docker version:  20.10.8

**Comment by jojju** [comment]
Hi, thanks for the report! Sorry, summer vacations caused some delay here. Someone will take a look at this shortly.

**Comment by jojju** [comment]
Hello again!

I suspect the problem lies in this part of the Docker documentation:

`echo subjectAltName = DNS:$HOST,IP:10.10.10.20,IP:127.0.0.1 >> extfile.cnf`

Since you are connecting using a raw IP address, that line should instead be:

`echo subjectAltName = IP:$HOST,IP:127.0.0.1 >> extfile.cnf`

Assuming the $HOST variable contains the IP address of your camera.

I hope this solves your problem!
