### ISSUE TITLE
Compatibility fail

### ISSUE THREAD

**Issue by masa126** [AxisCommunications/docker-acap#88]
Dear sir,
For the 1st step to install docker-acap on my P1467-LE, I performed the following commands as your readme.md.
 curl -s --anyauth -u "root:$DEVICE_PASSWORD" \
  "http://$DEVICE_IP/axis-cgi/param.cgi?action=update&root.Network.SSH.Enabled=yes"
ssh root@$DEVICE_IP 'command -v containerd >/dev/null 2>&1 && echo Compatible with Docker ACAP || echo Not compatible with Docker ACAP'
But P1467 responded "Not compatible with Docker ACAP"
When I follow the procedures written in "A pose estimator example application on an edge device" stored in "acap-computer-vision-sdk-examples", I encountered this issue at the beginning.
Is P1467 really not compatible with Docker ACAP?
Here I attached the response from P1467.
![ACAP_compatibility_check](https://user-images.githubusercontent.com/50834087/215634494-485a1c31-e3d8-40c9-b90f-52f11b32d651.png)
Thank you,

**Comment by florianwns** [comment]
Hi, I have the same problem with my Q1798-LE camera.

In the ACAP 4 documentation, I can read that our cameras are compatible.
https://axiscommunications.github.io/acap-documentation/docs/axis-devices-and-compatibility#sdk-and-device-compatibility

But in fact, it doesn't work at all.
Indeed `containerd` is not installed by default.

I installed the latest firmware 11.2.6, as well as Docker Acap,
but when i want to start acap docker app on my camera. it still does not work.

Could you explain the procedure, or tell us if our cameras are really compatible, because the documentation specifies that they are compatible with SDK computer vision, but that doesn't seem to be the case. Or maybe it's compatible only with the c++ part and not the docker part.

Thank you for your understanding.

**Comment by jojju** [comment]
@masa126 It seems to me that your camera should be compatible. What exact firmware version are you using?

@florianwns As far as I can tell, containerd ought to be included in your firmware but when I look at what's actually included it's not there. We will look into why that is the case and get back to you.

**Comment by masa126** [comment]
Its version is 10.11.59.
Your Object Analytics works well on this Cam.
My question is whether I should install docke-acap on my P1467 to test the procedure written in the readme.md of "A pose estimator example application on an edge device" or not.
If it is yes, please let me know the way to install it on P1467.

**Comment by florianwns** [comment]
Thx a lot @jojju ! 
If you manage to find why containerd is missing, I will be very grateful to you

**Comment by jojju** [comment]
@masa126 It looks like containerd is for some reason not included in the firmware version you are using, but it is included in later versions such as 11.2.61 found on the Axis site.

@florianwns After some investigation, I see now that Q1798-LE is in fact not supported, so the documentation is wrong. The confusion comes from the fact that there is an upcoming version of that camera where container support _is_ included. Sorry about this! I will request for the documentation to be corrected.
